name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "20"
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        working-directory: ./packages/hlogr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
